# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 4.1.0 ]
  pull_request:
    branches: [ 4.1.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: check remote updates
      id: commit
      run: |
       export TS_COMMIT=$(git rev-parse --short $(curl --silent https://api.github.com/repos/oracle/graal/commits/master | jq .sha | xargs))
       echo $TS_COMMIT
       echo "::set-output name=hash::$TS_COMMIT"
    - name: Cache git clone oracle/graal
      id: cache
      uses: actions/cache@v2.1.1
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: built
        key: ${{ steps.commit.outputs.hash }}
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.cache.outputs.cache-hit != 'trues'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: wget https://patch-diff.githubusercontent.com/raw/microsoft/TypeScript/pull/40068.patch
    - run: wget https://github.com/microsoft/TypeScript/archive/master.tar.gz
    - run: |
        git config --global user.email "frank@dspeed.eu"
        git config --global user.name "Frank Lemanschik"
        echo Hi ${{ steps.commit.outputs.hash }}
        tar xf master.tar.gz
        cd TypeScript-master
        git init
        git add src
        git commit -am "${{ steps.commit.outputs.hash }}"
        git apply ../40068.patch
        git commit -am "Patched: "
        npm install gulp fancy-log
        npm run build:compiler
        npm test
    - run: |
        cd built
        mv local typescript-${{ steps.commit.outputs.hash }}
        tar cvf - graalvm-ce-java15-20.3.0-dev | gzip -9 - > ../typescript-${{ steps.commit.outputs.hash }}.tar.gz
